apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}-config
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  VERSION: {{ .Values.config.version | quote }}
