{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  labels:
    app: migrate
    {{- include "lab.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.migrate.backoffLimit }}
  template:
    metadata:
      labels:
        app: migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_MODE
              value: "migrate"
            - name: APP_NAME
              value: "migrate"
            - name: VERSION
              value: "2.0.0"
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
{{- end }}
