apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
    {{- include "lab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        {{- include "lab.labels" . | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.common.port }}
          env:
            {{- range $name, $value := .Values.worker.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.common.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
